services:
  web:
    build: .
    ports:
      - "3001:3001"

    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
            - .next/
            - .git/
        - action: rebuild
          path: package.json
        - action: rebuild
          path: bun.lock
